import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import invoicesRouter from "./invoices";
import deadlinesRouter from "./deadlines";
import estimatesRouter from "./estimates";
import dashboardRouter from "./dashboard";
import clientsRouter from "./clients";
import teamRouter from "./team";
import timeEntriesRouter from "./time-entries";
import projectTasksRouter from "./project-tasks";
import reportsRouter from "./reports";
import authRouter from "./auth";
import expensesRouter from "./expenses";
import deliverablesRouter from "./deliverables";
import manualRouter from "./manual";
import accountingRouter from "./accounting";
import vendorsRouter from "./vendors";
import productsRouter from "./products";
import proposalsRouter from "./proposals";
import contractsRouter from "./contracts";
import crmRouter from "./crm";
import creativeRouter from "./creative";
import billingRouter from "./billing";
import employeesRouter from "./employees";
import geminiRouter from "./gemini";
import accountingAiRouter from "./accounting-ai";
import mockupsRouter from "./mockups";
import scriptsRouter from "./scripts";
import dollyRouter from "./dolly";
import sharonRouter from "./sharon";
import geoffreyRouter from "./geoffrey";
import productionRouter from "./production";
import stripePaymentsRouter from "./stripe-payments";
import socialMediaRouter from "./social-media";
import workspaceRouter from "./workspace";
import gameStudioRouter from "./game-studio";
import testingLabRouter from "./testing-lab";
import dataPortabilityRouter from "./data-portability";
import podcastRouter from "./podcast";
import musicRouter from "./music";
import agentHubRouter from "./agent-hub";
import financialReportsRouter from "./financial-reports";
import reportEmailSettingsRouter from "./report-email-settings";
import anettaRouter from "./anetta";
import emailInboxRouter from "./email-inbox";
import employeeNotesRouter from "./employee-notes";
import { contactsRouter } from "./contacts";
import scriptwriterRouter from "./scriptwriter";
import gamingYoutubeRouter from "./gaming-youtube";
import oliveRouter from "./olive";
import summerRouter from "./summer";
import bentleyRouter from "./bentley";
import grantProposalsRouter from "./grant-proposals";
import stocksRouter from "./stocks";
import adminHealthRouter from "./admin-health";
import adminSeedRouter from "./admin-seed";
import agentCanvasRouter from "./agent-canvas";
import ttsRouter from "./tts";
import approvalsRouter from "./approvals";
import campaignsRouter from "./campaigns";
import demoRouter from "./demo";
import trialsRouter from "./trials";
import outreachRouter from "./outreach";
import automationRouter from "./automation";
import pbxNumbersRouter from "./pbx-numbers";
import pbxExtensionsRouter from "./pbx-extensions";
import pbxWebhooksRouter from "./pbx-webhooks";
import pbxCallsRouter from "./pbx-calls";
import pbxSmsRouter from "./pbx-sms";
import pbxVoicemailsRouter from "./pbx-voicemails";
import calendarRouter from "./calendar";
import calendarSettingsRouter from "./calendar-settings";
import itDepartmentRouter from "./it-department";
import inventorsRouter from "./inventors";
import socialDeptRouter from "./social-dept";
import imageGenRouter from "./image-gen";
import eventBusRouter from "./event-bus";

const router: IRouter = Router();

router.use("/auth", authRouter);
router.use(healthRouter);
router.use(projectsRouter);
router.use(invoicesRouter);
router.use(deadlinesRouter);
router.use(estimatesRouter);
router.use(dashboardRouter);
router.use(clientsRouter);
router.use(teamRouter);
router.use(timeEntriesRouter);
router.use(projectTasksRouter);
router.use(reportsRouter);
router.use(expensesRouter);
router.use(deliverablesRouter);
router.use(accountingRouter);
router.use(vendorsRouter);
router.use(proposalsRouter);
router.use(contractsRouter);
router.use(crmRouter);
router.use(creativeRouter);
router.use(billingRouter);
router.use(employeesRouter);
router.use(geminiRouter);
router.use(accountingAiRouter);
router.use(mockupsRouter);
router.use(scriptsRouter);
router.use(dollyRouter);
router.use(sharonRouter);
router.use(geoffreyRouter);
router.use(productionRouter);
router.use(manualRouter);
router.use(stripePaymentsRouter);
router.use(socialMediaRouter);
router.use(workspaceRouter);
router.use(gameStudioRouter);
router.use(testingLabRouter);
router.use(dataPortabilityRouter);
router.use(podcastRouter);
router.use(musicRouter);
router.use(agentHubRouter);
router.use(financialReportsRouter);
router.use(reportEmailSettingsRouter);
router.use(anettaRouter);
router.use(employeeNotesRouter);
router.use(emailInboxRouter);
router.use(contactsRouter);
router.use(scriptwriterRouter);
router.use(gamingYoutubeRouter);
router.use(oliveRouter);
router.use(summerRouter);
router.use(bentleyRouter);
router.use(grantProposalsRouter);
router.use(stocksRouter);
router.use(adminHealthRouter);
router.use(adminSeedRouter);
router.use(agentCanvasRouter);
router.use(productsRouter);
router.use(ttsRouter);
router.use(approvalsRouter);
router.use(campaignsRouter);
router.use(demoRouter);
router.use(trialsRouter);
router.use(outreachRouter);
router.use(automationRouter);
router.use("/pbx", pbxNumbersRouter);
router.use("/pbx", pbxExtensionsRouter);
router.use("/pbx", pbxWebhooksRouter);
router.use("/pbx", pbxCallsRouter);
router.use("/pbx", pbxSmsRouter);
router.use("/pbx", pbxVoicemailsRouter);
router.use(calendarRouter);
router.use(calendarSettingsRouter);
router.use(itDepartmentRouter);
router.use(inventorsRouter);
router.use(socialDeptRouter);
router.use(imageGenRouter);
router.use(eventBusRouter);

export default router;
